# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server_services_pb2 as server__services__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SendFileServiceStub(object):
    """Serviço SendFileService para envio de arquivos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFile = channel.unary_unary(
                '/server_services.SendFileService/SendFile',
                request_serializer=server__services__pb2.SendFileRequestBody.SerializeToString,
                response_deserializer=server__services__pb2.SendFileResponseBody.FromString,
                _registered_method=True)
        self.SendFileChunks = channel.stream_unary(
                '/server_services.SendFileService/SendFileChunks',
                request_serializer=server__services__pb2.SendFileChunksRequest.SerializeToString,
                response_deserializer=server__services__pb2.SendFileChunksResponse.FromString,
                _registered_method=True)


class SendFileServiceServicer(object):
    """Serviço SendFileService para envio de arquivos
    """

    def SendFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFileChunks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFile,
                    request_deserializer=server__services__pb2.SendFileRequestBody.FromString,
                    response_serializer=server__services__pb2.SendFileResponseBody.SerializeToString,
            ),
            'SendFileChunks': grpc.stream_unary_rpc_method_handler(
                    servicer.SendFileChunks,
                    request_deserializer=server__services__pb2.SendFileChunksRequest.FromString,
                    response_serializer=server__services__pb2.SendFileChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_services.SendFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('server_services.SendFileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SendFileService(object):
    """Serviço SendFileService para envio de arquivos
    """

    @staticmethod
    def SendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.SendFileService/SendFile',
            server__services__pb2.SendFileRequestBody.SerializeToString,
            server__services__pb2.SendFileResponseBody.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFileChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/server_services.SendFileService/SendFileChunks',
            server__services__pb2.SendFileChunksRequest.SerializeToString,
            server__services__pb2.SendFileChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileServiceStub(object):
    """Serviço FileService para processamento de CSV, validação de XML e consulta de estados
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessCSV = channel.unary_unary(
                '/server_services.FileService/ProcessCSV',
                request_serializer=server__services__pb2.CSVRequest.SerializeToString,
                response_deserializer=server__services__pb2.CoordinatesResponse.FromString,
                _registered_method=True)
        self.GetStatesByCountry = channel.unary_unary(
                '/server_services.FileService/GetStatesByCountry',
                request_serializer=server__services__pb2.CountryRequest.SerializeToString,
                response_deserializer=server__services__pb2.StatesResponse.FromString,
                _registered_method=True)
        self.ConvertCSVToXML = channel.unary_unary(
                '/server_services.FileService/ConvertCSVToXML',
                request_serializer=server__services__pb2.ConvertCSVToXMLRequest.SerializeToString,
                response_deserializer=server__services__pb2.ConvertCSVToXMLResponse.FromString,
                _registered_method=True)
        self.ConvertXMLToXSD = channel.unary_unary(
                '/server_services.FileService/ConvertXMLToXSD',
                request_serializer=server__services__pb2.ConvertXMLToXSDRequest.SerializeToString,
                response_deserializer=server__services__pb2.ConvertXMLToXSDResponse.FromString,
                _registered_method=True)
        self.ConvertXMLToDatabase = channel.unary_unary(
                '/server_services.FileService/ConvertXMLToDatabase',
                request_serializer=server__services__pb2.ConvertXMLToDatabaseRequest.SerializeToString,
                response_deserializer=server__services__pb2.GenericResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Serviço FileService para processamento de CSV, validação de XML e consulta de estados
    """

    def ProcessCSV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatesByCountry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertCSVToXML(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertXMLToXSD(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertXMLToDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessCSV': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessCSV,
                    request_deserializer=server__services__pb2.CSVRequest.FromString,
                    response_serializer=server__services__pb2.CoordinatesResponse.SerializeToString,
            ),
            'GetStatesByCountry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatesByCountry,
                    request_deserializer=server__services__pb2.CountryRequest.FromString,
                    response_serializer=server__services__pb2.StatesResponse.SerializeToString,
            ),
            'ConvertCSVToXML': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertCSVToXML,
                    request_deserializer=server__services__pb2.ConvertCSVToXMLRequest.FromString,
                    response_serializer=server__services__pb2.ConvertCSVToXMLResponse.SerializeToString,
            ),
            'ConvertXMLToXSD': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertXMLToXSD,
                    request_deserializer=server__services__pb2.ConvertXMLToXSDRequest.FromString,
                    response_serializer=server__services__pb2.ConvertXMLToXSDResponse.SerializeToString,
            ),
            'ConvertXMLToDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertXMLToDatabase,
                    request_deserializer=server__services__pb2.ConvertXMLToDatabaseRequest.FromString,
                    response_serializer=server__services__pb2.GenericResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_services.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('server_services.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Serviço FileService para processamento de CSV, validação de XML e consulta de estados
    """

    @staticmethod
    def ProcessCSV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.FileService/ProcessCSV',
            server__services__pb2.CSVRequest.SerializeToString,
            server__services__pb2.CoordinatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatesByCountry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.FileService/GetStatesByCountry',
            server__services__pb2.CountryRequest.SerializeToString,
            server__services__pb2.StatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertCSVToXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.FileService/ConvertCSVToXML',
            server__services__pb2.ConvertCSVToXMLRequest.SerializeToString,
            server__services__pb2.ConvertCSVToXMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertXMLToXSD(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.FileService/ConvertXMLToXSD',
            server__services__pb2.ConvertXMLToXSDRequest.SerializeToString,
            server__services__pb2.ConvertXMLToXSDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertXMLToDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.FileService/ConvertXMLToDatabase',
            server__services__pb2.ConvertXMLToDatabaseRequest.SerializeToString,
            server__services__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
