version: "3.8"
services: 
  grpc-server: 
    build: ./grpc-server 
    container_name: grpc-server 
    ports: 
      - "50051:50051" 
    volumes: 
      - grpc-server:/app/media 
      - ./data/media:/app/media 
    environment: 
      - GRPC_SERVER_PORT=50051 
      - MAX_WORKERS=10 
      - MEDIA_PATH=/app/media 
      - DBNAME=mydatabase 
      - DBUSERNAME=myuser 
      - DBPASSWORD=mypassword 
      - DBHOST=db 
      - DBPORT=5432 
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PW=password
    depends_on: 
      - db 
    networks:
      - app_network
  
  rest-api-server:
    build: ./rest_api_server 
    container_name: rest_api_server 
    ports: 
      - "8000:8000"
    volumes: 
      - ./data/media:/app/media 
    environment: 
      - GRPC_PORT=50051 
      - GRPC_HOST=grpc-server 
      - DBNAME=mydatabase 
      - DBUSERNAME=myuser 
      - DBPASSWORD=mypassword 
      - DBHOST=db 
      - DBPORT=5432
    depends_on:
      - grpc-server
      - db
    networks:
      - app_network
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app_network
  

  db:
    image: postgres:latest 
    container_name: postgres-db 
    environment: 
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: mydatabase 
    ports: 
      - "5438:5432" 
    volumes: 
      - pgdata:/var/lib/postgresql/data  
    networks:
      - app_network

  worker:
    build: ./worker-rabbit-csv
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
      - db
      - grpc-server
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PW=password
      - DBNAME=mydatabase
      - DBUSERNAME=myuser
      - DBPASSWORD=mypassword
      - DBHOST=db
      - DBPORT=5432
    restart: on-failure
    networks:
      - app_network
    
  graphql-server:
    build: ./graphql-server
    container_name: graphql-server
    ports:
      - "9000:9000"
    volumes:
      - ./graphql-server:/app
    environment:
      - DBNAME=mydatabase
      - DBUSERNAME=myuser
      - DBPASSWORD=mypassword
      - DBHOST=db
      - DBPORT=5432
    depends_on:
      - db
    networks:
      - app_network

volumes: 
  grpc-server: 
  pgdata:
  rabbitmq-data:

networks:
  app_network:
    driver: bridge
